### PR TITLE
blender exporter

### PR DESCRIPTION
**Pull request by MaherRayes**
Added a blender exporter plugin.

### CODE REVIEW

**Comment by PearCoding** [comment]
Thanks for the PR. However, could you get rid of the preview render stuff? Just delete IgnisRenderEngine, IgnisWorld and all the binary stuff. There is no need to have a preview inside Blender. Just exporting the scene as a file is sufficient for now.

**Comment by MaherRayes** [comment]
The issue is that Seesharp plugin uses the information from the render engine to capture the background and convert the materials to prinicipled material. I don't think I can simply get rid of it.
I guess I will look if there is a workaround.

**Comment by PearCoding** [comment]
The plugin does not have to depend on SeeSharp. Just exporting the meshes and mapping materials, lights etc is sufficient. The background is essentially also just a material. If the given "node" is a color it will be just a constant environment map, if it is a texture, it will be a textured environment map. I would suggest to drop the environment thingy. I can add it afterwards, as I already did that on some prior projects and it does not take much time.

**Comment by PearCoding** [comment]
Looks good. Thanks!

**Pull request merged**
